name: Security Scan Pipeline

on:
  push:
    branches:
    
  # pull_request:
  #   branches:
  #     - main
  #     - master
  # workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  sast-codeql:
    name: SAST - CodeQL
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     language:
    #       - javascript
    #       - python
    #       - java

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          
       - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sca-trivy:
    name: SCA - Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"

      # - name: Upload Trivy Results
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: trivy-results.sarif

  secret-detection:
    name: Secret Detection - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # security-gate:
  #   name: Security Quality Gate
  #   runs-on: ubuntu-latest
  #   needs:
  #     - sast-codeql
  #     - sca-trivy
  #     - secret-detection

  #   steps:
  #     - name: Security Checks Passed
  #       run: |
  #         echo "All security scans completed successfully."
